services:
  broker:
    build: ./broker-ee
    environment:
      HIVEMQ_LOG_LEVEL: DEBUG
    ports:
      - published: 1883
        target: 1883
      - published: 8888
        target: 8888
      - published: 8080
        target: 8080
    restart: unless-stopped

  retained-message-generator:
    build: ./retained-message-generator
    depends_on:
      - broker
    environment:
      PORT: 3000
    ports:
      - published: 3000
        target: 3000
    restart: unless-stopped
